# Generated by Django 4.2.16 on 2024-10-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_atual', to='produtos.produto')),
            ],
            options={
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('numero_nota', models.CharField(max_length=20)),
                ('imei', models.CharField(blank=True, max_length=20, null=True)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda_unitaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('venda_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='estoque.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='produtos.produto')),
            ],
            options={
                'verbose_name_plural': 'Entradas de Estoque',
            },
        ),
    ]
