# Generated by Django 4.2.16 on 2024-10-28 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_corproduto_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estoque', '0004_alter_entradaestoque_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradaestoque',
            options={'verbose_name': 'Entrada de Estoque', 'verbose_name_plural': 'Entradas de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['quantidade_disponivel'], 'verbose_name_plural': 'Estoques'},
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='venda_total',
        ),
        migrations.AddField(
            model_name='entradaestoque',
            name='serializado',
            field=models.BooleanField(default=False, verbose_name='Serializado'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='data_entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='estoque.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='numero_nota',
            field=models.CharField(max_length=20, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='entradaestoque',
            name='venda_unitaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venda Unitária'),
        ),
        migrations.CreateModel(
            name='EstoqueImei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(max_length=20, verbose_name='IMEI')),
                ('vendido', models.BooleanField(default=False, verbose_name='Vendido')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_imei', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Estoque IMEI',
                'verbose_name_plural': 'Estoques IMEI',
            },
        ),
    ]
