# Generated by Django 4.2.16 on 2024-10-28 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_corproduto_criado_por_and_more'),
        ('estoque', '0005_alter_entradaestoque_options_alter_estoque_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaestoque',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='custo_unitario',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='serializado',
        ),
        migrations.RemoveField(
            model_name='entradaestoque',
            name='venda_unitaria',
        ),
        migrations.CreateModel(
            name='ProdutoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serializado', models.BooleanField(default=False, verbose_name='Serializado')),
                ('imei', models.CharField(blank=True, max_length=20, null=True, verbose_name='IMEI')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário')),
                ('venda_unitaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Venda Unitária')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque.entradaestoque', verbose_name='Entrada de Estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto na Entrada de Estoque',
                'verbose_name_plural': 'Produtos na Entrada de Estoque',
            },
        ),
    ]
