# Generated by Django 4.2.16 on 2024-10-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_entradaestoque_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtoentrada',
            name='serializado',
        ),
    ]
