# Generated by Django 4.2.16 on 2024-10-29 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_entradaestoque_criado_em_entradaestoque_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueimei',
            name='produto_entrada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_imei', to='estoque.produtoentrada'),
        ),
    ]
