# Generated by Django 4.2.16 on 2024-10-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_estoqueimei_produto_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueimei',
            name='produto_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estoque_imei', to='estoque.produtoentrada'),
        ),
    ]
