# Generated by Django 4.2.16 on 2024-10-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_estoqueimei_produto_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoentrada',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
