# Generated by Django 4.2.16 on 2024-12-15 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_produto_serializado'),
        ('vendas', '0013_loja_usuarios'),
        ('estoque', '0013_alter_produtoentrada_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('loja', 'produto')},
        ),
    ]
