# Generated by Django 4.2.16 on 2025-01-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_corproduto_loja_alter_estadoproduto_loja_and_more'),
        ('vendas', '0026_alter_caixa_loja_alter_cliente_loja_and_more'),
        ('estoque', '0017_alter_entradaestoque_loja_alter_estoqueimei_loja_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoqueimei',
            unique_together={('imei', 'produto', 'loja')},
        ),
    ]
