# Generated by Django 4.2.16 on 2025-01-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0026_alter_caixa_loja_alter_cliente_loja_and_more'),
        ('estoque', '0018_alter_estoqueimei_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
        ),
    ]
