# Generated by Django 4.2.16 on 2025-01-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_corproduto_loja_alter_estadoproduto_loja_and_more'),
        ('estoque', '0019_alter_estoque_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_atual', to='produtos.produto'),
        ),
    ]
