# Generated by Django 4.2.16 on 2024-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_corproduto_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='serializado',
            field=models.BooleanField(default=False),
        ),
    ]
