# Generated by Django 4.2.16 on 2024-12-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_serializado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='serializado',
        ),
    ]
