# Generated by Django 4.2.16 on 2024-12-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0019_caixa_loja_cliente_loja_comprovantescliente_loja_and_more'),
        ('produtos', '0006_remove_produto_serializado'),
    ]

    operations = [
        migrations.AddField(
            model_name='corproduto',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoproduto',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabricante',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoriaproduto',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
    ]
