# Generated by Django 4.2.16 on 2024-12-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_alter_corproduto_loja_alter_estadoproduto_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_cor', to='produtos.corproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_estado', to='produtos.estadoproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='memoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_memoria', to='produtos.memoriaproduto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_tipo', to='produtos.tipoproduto'),
        ),
    ]
