# Generated by Django 4.2.16 on 2025-01-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_alter_corproduto_loja_alter_estadoproduto_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
