# Generated by Django 4.2.16 on 2025-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='assistencia',
            field=models.BooleanField(default=False),
        ),
    ]
