# Generated by Django 4.2.16 on 2025-03-28 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0041_alter_venda_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0013_alter_produto_codigo'),
        ('assistencia', '0002_alter_caixaassistencia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.IntegerField(blank=True, null=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_cliente', to=settings.AUTH_USER_MODEL)),
                ('cor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_cor', to='produtos.corproduto')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_estado', to='produtos.estadoproduto')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_fabricante', to='produtos.fabricante')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistencia_produto_loja', to='vendas.loja')),
                ('memoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_memoria', to='produtos.memoriaproduto')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_assistencia_tipo', to='produtos.tipoproduto')),
            ],
            options={
                'verbose_name_plural': 'Produtos Assistência',
            },
        ),
    ]
