# Generated by Django 4.2.16 on 2025-03-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_produtoassistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.CharField(max_length=100)),
                ('defeito_relato', models.TextField()),
                ('status', models.CharField(choices=[('AGUARDANDO_PECAS', 'Aguardando Peças'), ('EM_TESTE', 'Em Teste'), ('SEM_CONSERTO', 'Sem Conserto'), ('FINALIZADA', 'Finalizada')], default='AGUARDANDO_PECAS', max_length=20)),
                ('mao_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valor_servico', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ordens de Serviço',
                'permissions': [('view_assistencia', 'Pode visualizar assistência')],
            },
        ),
        migrations.DeleteModel(
            name='ProdutoAssistencia',
        ),
    ]
