# Generated by Django 4.2.16 on 2025-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_alter_produto_codigo'),
        ('assistencia', '0004_ordemservico_delete_produtoassistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, related_name='pecas_os', to='produtos.produto'),
        ),
    ]
