# Generated by Django 4.2.16 on 2025-04-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0041_alter_venda_options'),
        ('assistencia', '0005_ordemservico_pecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico_loja', to='vendas.loja'),
        ),
    ]
