# Generated by Django 4.2.16 on 2025-04-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0006_ordemservico_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('Aguardando Peças', 'Aguardando Peças'), ('Em Teste', 'Em Teste'), ('Sem Conserto', 'Sem Conserto'), ('Finalizada', 'Finalizada')], default='AGUARDANDO_PECAS', max_length=20),
        ),
    ]
