# Generated by Django 4.2.16 on 2025-04-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0008_ordemservico_criado_em_ordemservico_criado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_entrada',
        ),
    ]
