# Generated by Django 4.2.16 on 2025-05-13 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0043_cliente_cliente_cred_facil_alter_cliente_bairro_and_more'),
        ('assistencia', '0009_remove_ordemservico_data_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico_cliente', to='vendas.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('EM MONTAGEM', 'Em Montagem'), ('EM TESTE', 'Em Teste'), ('SEM CONSERTO', 'Sem Conserto'), ('FINALIZADA', 'Finalizada')], default='EM MONTAGEM', max_length=20),
        ),
    ]
