# Generated by Django 4.2.16 on 2025-05-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_tipoproduto_assistencia'),
        ('assistencia', '0010_ordemservico_cliente_alter_ordemservico_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='pecas',
        ),
        migrations.CreateModel(
            name='PecaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistencia.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_ordem_servico', to='produtos.produto')),
            ],
            options={
                'verbose_name_plural': 'Peças por Ordem de Serviço',
                'permissions': [('view_assistencia', 'Pode visualizar assistência')],
            },
        ),
    ]
