# Generated by Django 4.2.16 on 2025-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_tipoproduto_assistencia'),
        ('assistencia', '0011_remove_ordemservico_pecas_pecaordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, related_name='ordem_servico_pecas', through='assistencia.PecaOrdemServico', to='produtos.produto'),
        ),
    ]
