# Generated by Django 4.2.16 on 2025-05-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_tipoproduto_assistencia'),
        ('assistencia', '0012_ordemservico_pecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='pecas',
            field=models.ManyToManyField(blank=True, through='assistencia.PecaOrdemServico', to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='pecaordemservico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_ordem_servico', to='assistencia.ordemservico'),
        ),
        migrations.AlterField(
            model_name='pecaordemservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_produto', to='produtos.produto'),
        ),
    ]
