# Generated by Django 4.2.16 on 2025-05-19 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0043_cliente_cliente_cred_facil_alter_cliente_bairro_and_more'),
        ('assistencia', '0013_alter_ordemservico_pecas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('data_primeira_parcela', models.DateField()),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='assistencia.ordemservico')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_assistencia_tipo', to='vendas.tipopagamento')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos Assistência',
            },
        ),
        migrations.CreateModel(
            name='ParcelaAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('numero_parcela', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('data_vencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_pagamento_assistencia', to='assistencia.pagamentoassistencia')),
                ('tipo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_assistencia_tipo', to='vendas.tipopagamento')),
            ],
            options={
                'verbose_name_plural': 'Parcelas Assistência',
            },
        ),
    ]
