# Generated by Django 4.2.16 on 2025-05-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0043_cliente_cliente_cred_facil_alter_cliente_bairro_and_more'),
        ('assistencia', '0014_pagamentoassistencia_parcelaassistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico_caixa', to='assistencia.caixaassistencia'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
        ),
    ]
