# Generated by Django 4.2.16 on 2025-05-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0015_ordemservico_caixa_alter_ordemservico_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
