# Generated by Django 4.2.16 on 2025-01-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_comissao_user_salario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salario',
        ),
    ]
