# Generated by Django 4.2.16 on 2025-01-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0038_tipopagamento_carne'),
        ('accounts', '0005_remove_user_comissao_remove_user_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.loja'),
        ),
    ]
