# Generated by Django 4.2.16 on 2024-10-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('rg', models.CharField(max_length=20)),
                ('cliente_cred_facil', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ComprovantesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identificacao_frente', models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/')),
                ('documento_identificacao_verso', models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/')),
                ('comprovante_residencia', models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/')),
                ('consulta_serasa', models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/')),
            ],
            options={
                'verbose_name_plural': 'Comprovantes Clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Informacoes Clientes',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('inscricao_estadual', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('meta_vendas_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_vendas_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada_caixa_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo_loja', models.ImageField(blank=True, null=True, upload_to='logos_lojas/')),
                ('mensagem_garantia', models.TextField(blank=True, null=True)),
                ('contrato', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_vendas', to='produtos.produto')),
            ],
            options={
                'verbose_name_plural': 'Produtos Vendas',
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Entrega',
            },
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caixa', models.BooleanField(default=False)),
                ('parcelas', models.BooleanField(default=False)),
                ('financeira', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='TipoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Vendas',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='vendas.cliente')),
                ('produtos', models.ManyToManyField(related_name='vendas', through='vendas.ProdutoVenda', to='produtos.produto')),
                ('tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_tipo_entrega', to='vendas.tipoentrega')),
                ('tipo_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_tipo_venda', to='vendas.tipovenda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='vendas.venda'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_primeira_parcela', models.DateField()),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_tipo', to='vendas.tipopagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='vendas.venda')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='ComprovantesCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_clientes', to='vendas.comprovantescliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacoes_clientes', to='vendas.endereco'),
        ),
    ]
