# Generated by Django 4.2.16 on 2024-10-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_alter_caixa_criado_por_alter_caixa_modificado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='total_vendas',
        ),
    ]
