# Generated by Django 4.2.16 on 2024-10-10 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_remove_caixa_total_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data_abertura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
