# Generated by Django 4.2.16 on 2024-10-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_caixa_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ComprovantesCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_clientes', to='vendas.comprovantescliente'),
        ),
    ]
