# Generated by Django 4.2.16 on 2024-10-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_alter_cliente_comprovantescliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_parcela',
        ),
    ]
