# Generated by Django 4.2.16 on 2024-10-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_remove_pagamento_valor_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovenda',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='produtovenda',
            name='modificado_por',
        ),
    ]
