# Generated by Django 4.2.16 on 2024-11-06 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0009_alter_caixa_criado_por_alter_caixa_modificado_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ComprovantesCliente',
            new_name='comprovantes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='888', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='belem', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='comprovante_residencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='consulta_serasa',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_frente',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comprovantescliente',
            name='documento_identificacao_verso',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes_clientes/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='ContatoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome_adicional', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato_adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contatos_adicionais', to='vendas.contatoadicional'),
        ),
    ]
