# Generated by Django 4.2.16 on 2024-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_rename_comprovantescliente_cliente_comprovantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtovenda',
            name='imei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtovenda',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
