# Generated by Django 4.2.16 on 2024-12-01 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0012_alter_loja_cnpj_alter_loja_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='usuarios',
            field=models.ManyToManyField(related_name='lojas', to=settings.AUTH_USER_MODEL),
        ),
    ]
