# Generated by Django 4.2.16 on 2024-12-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_alter_pagamento_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
