# Generated by Django 4.2.16 on 2024-12-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_parcela_valor_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='tipo_pagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_tipo_pagamento', to='vendas.tipopagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
