# Generated by Django 4.2.16 on 2024-12-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_parcela_tipo_pagamento_alter_parcela_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='tipo_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_tipo_pagamento', to='vendas.tipopagamento'),
        ),
    ]
