# Generated by Django 4.2.16 on 2024-12-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_alter_parcela_tipo_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
