# Generated by Django 4.2.16 on 2024-12-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_parcela_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprovantescliente',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contatoadicional',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcela',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoentrega',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopagamento',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipovenda',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
    ]
