# Generated by Django 4.2.16 on 2024-12-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_alter_caixa_loja_alter_cliente_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
