# Generated by Django 4.2.16 on 2024-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0021_venda_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
    ]
