# Generated by Django 4.2.16 on 2025-01-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0023_alter_venda_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
