# Generated by Django 4.2.16 on 2025-01-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0024_venda_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoadicional',
            name='contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contatoadicional',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contatoadicional',
            name='nome_adicional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
