# Generated by Django 4.2.16 on 2025-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0028_produtovenda_criado_em_produtovenda_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='contrato',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
