# Generated by Django 4.2.16 on 2025-01-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0032_alter_loja_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('can_more_desconto', 'Pode dar mais desconto'),), 'verbose_name_plural': 'Vendas'},
        ),
    ]
