# Generated by Django 4.2.16 on 2025-01-14 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0033_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='gerentes',
            field=models.ManyToManyField(related_name='lojas_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
