# Generated by Django 4.2.16 on 2025-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0034_loja_gerentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
