# Generated by Django 4.2.16 on 2025-01-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0035_cliente_endereco_cliente_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatoadicional',
            old_name='endereco',
            new_name='endereco_adicional',
        ),
    ]
