# Generated by Django 4.2.16 on 2025-01-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0037_alter_cliente_bairro_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopagamento',
            name='carne',
            field=models.BooleanField(default=False),
        ),
    ]
