# Generated by Django 4.2.16 on 2025-02-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0038_tipopagamento_carne'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopagamento',
            name='nao_contabilizar',
            field=models.BooleanField(default=False),
        ),
    ]
