# Generated by Django 4.2.16 on 2025-03-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0040_lancamentocaixatotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('can_more_desconto', 'Pode dar mais desconto'), ('can_generate_report_sale', 'Pode gerar relatório de vendas')), 'verbose_name_plural': 'Vendas'},
        ),
    ]
