# Generated by Django 4.2.16 on 2024-10-09 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0002_alter_gastofixo_options_gastofixo_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastofixo',
            name='criado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gastofixo',
            name='modificado_por',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
