# Generated by Django 4.2.16 on 2024-12-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_caixamensal_remove_funcionario_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamensal',
            name='funcionarios',
            field=models.ManyToManyField(through='financeiro.LojaFuncionario', to='financeiro.funcionario'),
        ),
        migrations.AddField(
            model_name='caixamensal',
            name='gasto_fixos',
            field=models.ManyToManyField(through='financeiro.LojaGastoFixo', to='financeiro.gastofixo'),
        ),
        migrations.AlterField(
            model_name='lojafuncionario',
            name='caixa_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loja_funcionarios', to='financeiro.caixamensal'),
        ),
        migrations.AlterField(
            model_name='lojafuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_funcionarios', to='financeiro.funcionario'),
        ),
        migrations.AlterField(
            model_name='lojagastofixo',
            name='gasto_fixo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lojas_gastos_fixos', to='financeiro.gastofixo'),
        ),
    ]
