# Generated by Django 4.2.16 on 2024-12-01 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0007_caixamensal_funcionarios_caixamensal_gasto_fixos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LojaFuncionario',
            new_name='CaixaMensalFuncionario',
        ),
        migrations.RenameModel(
            old_name='LojaGastoFixo',
            new_name='CaixaMensalGastoFixo',
        ),
    ]
