# Generated by Django 4.2.16 on 2024-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_rename_lojafuncionario_caixamensalfuncionario_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caixamensalgastofixo',
            constraint=models.UniqueConstraint(fields=('caixa_mensal', 'gasto_fixo'), name='unique_gasto_fixo_por_caixa_mensal'),
        ),
    ]
