# Generated by Django 4.2.16 on 2024-12-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_caixamensalgastofixo_unique_gasto_fixo_por_caixa_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixamensal',
            name='funcionarios',
            field=models.ManyToManyField(related_name='caixas_mensais', through='financeiro.CaixaMensalFuncionario', to='financeiro.funcionario'),
        ),
        migrations.AlterField(
            model_name='caixamensal',
            name='gasto_fixos',
            field=models.ManyToManyField(related_name='caixas_mensais', through='financeiro.CaixaMensalGastoFixo', to='financeiro.gastofixo'),
        ),
        migrations.AlterField(
            model_name='caixamensalfuncionario',
            name='caixa_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.caixamensal'),
        ),
        migrations.AlterField(
            model_name='caixamensalfuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.funcionario'),
        ),
        migrations.AlterField(
            model_name='caixamensalgastofixo',
            name='caixa_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.caixamensal'),
        ),
        migrations.AlterField(
            model_name='caixamensalgastofixo',
            name='gasto_fixo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.gastofixo'),
        ),
    ]
