# Generated by Django 4.2.16 on 2024-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_caixamensal_funcionarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixamensal',
            name='funcionarios',
        ),
        migrations.RemoveField(
            model_name='caixamensal',
            name='gasto_fixos',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='caixa_mensal',
            field=models.ManyToManyField(related_name='funcionarios', through='financeiro.CaixaMensalFuncionario', to='financeiro.caixamensal'),
        ),
        migrations.AddField(
            model_name='gastofixo',
            name='caixa_mensal',
            field=models.ManyToManyField(related_name='gastos_fixos', through='financeiro.CaixaMensalGastoFixo', to='financeiro.caixamensal'),
        ),
    ]
