# Generated by Django 4.2.16 on 2024-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_remove_caixamensal_funcionarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='caixa_mensal',
        ),
        migrations.RemoveField(
            model_name='gastofixo',
            name='caixa_mensal',
        ),
        migrations.AddField(
            model_name='caixamensal',
            name='funcionarios',
            field=models.ManyToManyField(related_name='funcionarios', through='financeiro.CaixaMensalFuncionario', to='financeiro.funcionario'),
        ),
        migrations.AddField(
            model_name='caixamensal',
            name='gastos_fixos',
            field=models.ManyToManyField(related_name='gastos_fixos', through='financeiro.CaixaMensalGastoFixo', to='financeiro.gastofixo'),
        ),
    ]
