# Generated by Django 4.2.16 on 2024-12-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0019_caixa_loja_cliente_loja_comprovantescliente_loja_and_more'),
        ('financeiro', '0013_remove_caixamensal_gastos_fixos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixamensalfuncionario',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixamensalgastofixo',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastofixo',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gastosaleatorios',
            name='loja',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_loja', to='vendas.loja'),
            preserve_default=False,
        ),
    ]
