# Generated by Django 4.2.16 on 2025-01-24 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financeiro', '0016_alter_caixamensalfuncionario_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixamensal',
            name='funcionarios',
            field=models.ManyToManyField(through='financeiro.CaixaMensalFuncionario', to='financeiro.caixamensal'),
        ),
        migrations.AlterField(
            model_name='caixamensalfuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
