# Generated by Django 4.2.16 on 2025-03-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_alter_caixamensal_funcionarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixamensal',
            name='gasto_fixos',
            field=models.ManyToManyField(related_name='gastos_fixos', through='financeiro.CaixaMensalGastoFixo', to='financeiro.gastofixo'),
        ),
        migrations.AlterField(
            model_name='caixamensalgastofixo',
            name='caixa_mensal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fixos_caixa_mensal', to='financeiro.caixamensal'),
        ),
    ]
